-- Function to update updated_at column automatically
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TABLE IF NOT EXISTS USERS (
    user_id SERIAL PRIMARY KEY NOT NULL,
    name_user VARCHAR(100) NOT NULL,
    lastname VARCHAR(50) NOT NULL,
    address VARCHAR(100) NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL,
    phone VARCHAR(20) UNIQUE NOT NULL,
    city VARCHAR(50) NOT NULL,
    country VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON USERS
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- status seria si esta activo o inactivo
CREATE TABLE IF NOT EXISTS PROVIDERS(
    provider_id SERIAL PRIMARY KEY NOT NULL,
    name_provider VARCHAR(100) NOT NULL,
    address VARCHAR(100) NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER update_providers_updated_at BEFORE UPDATE ON PROVIDERS
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TABLE IF NOT EXISTS CATEGORIES(
    category_id SERIAL PRIMARY KEY NOT NULL,
    name_category VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER update_categories_updated_at BEFORE UPDATE ON CATEGORIES
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- STATUS DE PRODUCTS SI ESTA (ACTIVE O INACTIVE)
CREATE TABLE IF NOT EXISTS PRODUCTS(
    products_id SERIAL PRIMARY KEY NOT NULL,
    category_id INT NOT NULL REFERENCES CATEGORIES(category_id),
    provider_id INT NOT NULL REFERENCES PROVIDERS(provider_id),
    name_product VARCHAR(100) NOT NULL,
    code INT UNIQUE NOT NULL,
    stock INT NOT NULL,
    cost_price NUMERIC(12,2) NOT NULL DEFAULT 0.00 CHECK (cost_price >= 0),
    sales_price NUMERIC(12,2) NOT NULL DEFAULT 0.00 CHECK (sales_price >= 0),
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER update_products_updated_at BEFORE UPDATE ON PRODUCTS
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TABLE IF NOT EXISTS ORDERS(
    orders_id SERIAL PRIMARY KEY NOT NULL,
    user_id INT NOT NULL REFERENCES USERS(user_id),
    employee_id INT, -- Logical relation to RRHH.EMPLOYEES
    shipping_cost NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    total_amount NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER update_orders_updated_at BEFORE UPDATE ON ORDERS
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TABLE IF NOT EXISTS PAYMENTS(
    payments_id SERIAL PRIMARY KEY NOT NULL,
    order_id INT NOT NULL REFERENCES ORDERS(orders_id),
    payment_method VARCHAR(50) NOT NULL,
    amount NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER update_payments_updated_at BEFORE UPDATE ON PAYMENTS
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TABLE IF NOT EXISTS ORDERS_DETAILS(
    details_id SERIAL PRIMARY KEY NOT NULL,
    products_id INT NOT NULL REFERENCES PRODUCTS(products_id),
    order_id INT NOT NULL REFERENCES ORDERS(orders_id),
    quantity INT NOT NULL,
    unit_price NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER update_orders_details_updated_at BEFORE UPDATE ON ORDERS_DETAILS
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

