services:
#####################################
# SERVICIO DE POSTGRESQL ECOMMERCE
#####################################
  db_ecommerce:
    image: postgres:latest
    ports:
      - "5432:5432"  
    volumes:
      - ./src/database/ecommerce:/docker-entrypoint-initdb.d/
      - postgres_ecommerce_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${ECOMMERCE_DB_NAME}
    networks:
      - data-network

#####################################
# SERVICIO DE POSTGRESQL RRHH
#####################################
  db_rrhh:
    image: postgres:latest
    ports:
      - "5433:5432"  
    volumes:
      - ./src/database/rrhh:/docker-entrypoint-initdb.d/
      - postgres_rrhh_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${RRHH_DB_NAME}
    networks:
      - data-network

#####################################
# SERVICIO DE POSTGRESQL MARKETING
#####################################
  db_marketing:
    image: postgres:latest
    ports:
      - "5434:5432"
    volumes:
      - ./src/database/marketing:/docker-entrypoint-initdb.d/
      - postgres_marketing_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${MARKETING_DB_NAME}
    networks:
      - data-network

#############################################################
# INTERFAZ GRAFICA DE PGADMIN4
############################################################
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: lmlisandro3@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - db_ecommerce
      - db_rrhh
      - db_marketing
    networks:
      - data-network

################################################
# SERVICIO DEL SIMULADOR
###############################################
  simulator:
    build:
      context: .
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    depends_on:
      - db_ecommerce
      - db_rrhh
      - db_marketing
    networks:
      - data-network


volumes:
  postgres_ecommerce_data:
  postgres_rrhh_data:
  postgres_marketing_data:

networks:
  data-network:
    external: true
