CREATE TABLE IF NOT EXISTS USERS (
    user_id SERIAL PRIMARY KEY NOT NULL,
    name VARCHAR(100) NOT NULL,
    lastname VARCHAR(50) NOT NULL,
    address VARCHAR(100) NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL,
    phone VARCHAR(11) UNIQUE NOT NULL,
    city VARCHAR(50) NOT NULL,
    country VARCHAR(50) NOT NULL,
    datetime TIMESTAMPTZ NOT NULL
);
-- status seria si esta activo o inactivo
CREATE TABLE IF NOT EXISTS PROVIDERS(
    provider_id SERIAL PRIMARY KEY NOT NULL,
    name_provider VARCHAR(100) NOT NULL,
    address VARCHAR(100) NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL,
    status VARCHAR(50) NOT NULL,
    datetime TIMESTAMPTZ  NOT NULL
);

CREATE TABLE IF NOT EXISTS CATEGORIES(
    category_id SERIAL PRIMARY KEY NOT NULL,
    name_category VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    datetime TIMESTAMPTZ NOT NULL
);
-- STATUS DE PRODUCTS SI ESTA (ACTIVE O INACTIVE)
CREATE TABLE IF NOT EXISTS PRODUCTS(
    products_id SERIAL PRIMARY KEY NOT NULL,
    category_id INT NOT NULL,
    provider_id INT NOT NULL,
    name_product VARCHAR(100) NOT NULL,
    code INT UNIQUE NOT NULL,
    stock INT NOT NULL,
    cost_price NUMERIC(12,2) NOT NULL DEFAULT 0.00 CHECK (cost_price >= 0),
    sales_price NUMERIC(12,2) NOT NULL DEFAULT 0.00 CHECK (sales_price >= 0),
    status VARCHAR(50) NOT NULL,
    datetime TIMESTAMPTZ NOT NULL
);
-- ESTE STATUS ES PARA SABE COMO ESTA EL PAGO SI ESTA (PENDIENTE, PAGADO)
CREATE TABLE IF NOT EXISTS PAYMENTS(
    payments_id SERIAL PRIMARY KEY NOT NULL,
    order_id INT NOT NULL,
    payment_method VARCHAR(50) NOT NULL,
    amount NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    status VARCHAR(50) NOT NULL,
    datetime TIMESTAMPTZ NOT NULL
);
-- ESTE STATUS DE ORDERS ES PARA VER LA ORDER SI ESTA (PENDIENTE, EN PROCESO DE ENVIO, CANCELADA)
CREATE TABLE IF NOT EXISTS ORDERS(
    orders_id SERIAL PRIMARY KEY NOT NULL,
    user_id INT NOT NULL,
    shipping_cost NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    total_amount NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    status VARCHAR(50) NOT NULL,
    datetime TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS ORDERS_DETAILS(
    details_id SERIAL PRIMARY KEY NOT NULL,
    products_id INT NOT NULL,
    order_id INT NOT NULL,
    quantity INT NOT NULL,
    unit_price NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    datetime TIMESTAMPTZ NOT NULL
);
