name: Data Generator E-commerce

on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:

jobs:
  insert-data-oltp:
    name: insertar data
    runs-on: ubuntu-latest
    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v3  

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar Dependencias
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generador de Datos
        env:
          NEON_DB_HOST: ${{ secrets.NEON_DB_HOST }}
          NEON_POSTGRES_USER: ${{ secrets.NEON_POSTGRES_USER }}
          NEON_POSTGRES_PASSWORD: ${{ secrets.NEON_POSTGRES_PASSWORD }}
          NEON_DATABASE: ${{ secrets.NEON_DATABASE }}
        run: python src/main.py   