name: Data Generator E-commerce

on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:

jobs:
  insert-data-oltp:
    name: insertar data
    runs-on: ubuntu-latest
    env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_NEON }}
    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v3  

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar Dependencias
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generador de Datos
        run: python src/main.py   