ALTER TABLE LEADS ADD CONSTRAINT fk_leads_campaign FOREIGN KEY (campaign_id) REFERENCES CAMPAIGNS(campaign_id);

ALTER TABLE CUSTOMER_SEGMENT_ASSIGNMENT ADD CONSTRAINT fk_assignment_segment FOREIGN KEY (segment_id) REFERENCES CUSTOMER_SEGMENTS(segment_id);

ALTER TABLE EMAIL_CAMPAIGN_EVENTS ADD CONSTRAINT fk_events_campaign FOREIGN KEY (campaign_id) REFERENCES CAMPAIGNS(campaign_id);
